%% Imported types

% Directions enumeration type.
Simulink.defineIntEnumType('Directions', ...
    {'Forward', 'Backward'}, ...
    [0; 1], ...
    'DefaultValue', 'Forward', ...
    'DataScope', 'Imported', ...
    'AddClassNameToEnumNames', false, ...
    'Description', 'QGen.AdaSpecFile:nxt-motors.ads');

% Power_Level type %
Power_Level = Simulink.AliasType;
Power_Level.BaseType = 'uint8';
Power_Level.Description = ...
    ['QGen.AdaSpecFile:nxt-motors.ads ', ...
     'QGen.ValueRange:[0, 100] '];

% Motor_Encoder_Counts type %
Motor_Encoder_Counts = Simulink.AliasType;
Motor_Encoder_Counts.BaseType = 'int32';
Motor_Encoder_Counts.Description = 'QGen.AdaSpecFile:nxt-motors.ads';
